spring:
  application:
    name: genderinfilm

  # Provide defaults to all the datasource properties even though the environment variables are all defined in the
  # compose file. We do this to allow running the app without Docker (which is helpful when testing locally).
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/genderinfilm}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none  # We use Liquibase instead.

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  # Property overrides for local testing
  config:
    import: local.properties

  # Allows us to call DELETE via a form
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  # Used to enable hot reloading of thymeleaf generated html pages.
  thymeleaf:
    cache: false